services:
  - type: web
    name: portfolio-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://my-portfolio-eight-ruddy-44.vercel.app
      - key: MONGODB_URI
        value: mongodb+srv://ranjith201099_db_user:q2mL2iYxspBZH7rK@ranjith-portfolio.zhuteug.mongodb.net/?appName=ranjith-Portfolio
      - key: GEMINI_API_KEY
        value: AIzaSyCJHDkwc67pkEGGw01HKlNHEVjV_rTlhtAv
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: ranjith201099@gmail.com
      - key: SMTP_PASS
        value: "ndur euro chof ejlh"
      - key: EMAIL_FROM
        value: "Portfolio <ranjith201099@gmail.com>"
      - key: NOTIFICATION_EMAIL
        value: ranjith201099@gmail.com
